[2023-05-05T18:21:58.611+0000] {processor.py:153} INFO - Started process (PID=4661) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:21:58.612+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:21:58.613+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:21:58.613+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:21:58.630+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:21:58.630+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:21:58.630+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:21:58.630+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:21:58.631+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:21:58.639+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-05-05T18:22:51.094+0000] {processor.py:153} INFO - Started process (PID=5044) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:22:51.095+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:22:51.097+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:22:51.097+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:22:51.120+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:22:51.120+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:22:51.121+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:22:51.121+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:22:51.121+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:22:51.129+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-05-05T18:23:40.161+0000] {processor.py:153} INFO - Started process (PID=5357) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:23:40.163+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:23:40.163+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:23:40.163+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:23:40.181+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:23:40.180+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:23:40.181+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:23:40.181+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:23:40.181+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:23:40.348+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.190 seconds
[2023-05-05T18:24:18.230+0000] {processor.py:153} INFO - Started process (PID=5624) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:24:18.231+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:24:18.232+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:24:18.231+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:24:18.251+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:24:18.250+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:24:18.251+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:24:18.251+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:24:18.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:24:18.259+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-05-05T18:24:58.408+0000] {processor.py:153} INFO - Started process (PID=5937) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:24:58.410+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:24:58.410+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:24:58.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:24:58.428+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:24:58.428+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:24:58.429+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:24:58.429+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:24:58.429+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:24:58.437+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-05-05T18:25:42.006+0000] {processor.py:153} INFO - Started process (PID=6225) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:25:42.007+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:25:42.008+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:25:42.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:25:42.026+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:25:42.025+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:25:42.026+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:25:42.026+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:25:42.026+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:25:42.035+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-05-05T18:26:23.666+0000] {processor.py:153} INFO - Started process (PID=6520) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:26:23.668+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:26:23.668+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:26:23.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:26:23.686+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:26:23.685+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:26:23.686+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:26:23.686+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:26:23.686+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:26:23.695+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-05-05T18:27:03.381+0000] {processor.py:153} INFO - Started process (PID=6791) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:27:03.382+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:27:03.383+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:27:03.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:27:03.400+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:27:03.400+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:27:03.400+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:27:03.400+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:27:03.401+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:27:03.410+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-05-05T18:27:39.839+0000] {processor.py:153} INFO - Started process (PID=7069) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:27:39.841+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:27:39.841+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:27:39.841+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:27:39.858+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:27:39.858+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:27:39.859+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:27:39.859+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:27:39.859+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:27:39.867+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-05-05T18:28:16.053+0000] {processor.py:153} INFO - Started process (PID=7562) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:28:16.054+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:28:16.055+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:28:16.055+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:28:16.074+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:28:16.073+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:28:16.074+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:28:16.074+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:28:16.074+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:28:16.083+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-05-05T18:28:55.986+0000] {processor.py:153} INFO - Started process (PID=8119) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:28:55.987+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:28:55.988+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:28:55.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:28:56.005+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:28:56.004+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:28:56.005+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:28:56.005+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:28:56.006+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:28:56.015+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-05-05T18:29:36.479+0000] {processor.py:153} INFO - Started process (PID=8455) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:29:36.480+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:29:36.481+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:29:36.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:29:36.499+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:29:36.499+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:29:36.499+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:29:36.499+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:29:36.500+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:29:36.508+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-05-05T18:30:14.389+0000] {processor.py:153} INFO - Started process (PID=8823) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:30:14.390+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:30:14.391+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:30:14.391+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:30:14.409+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:30:14.409+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:30:14.410+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:30:14.410+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:30:14.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:30:14.419+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-05-05T18:30:52.057+0000] {processor.py:153} INFO - Started process (PID=9138) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:30:52.059+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:30:52.059+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:30:52.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:30:52.077+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:30:52.077+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:30:52.078+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:30:52.077+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:30:52.078+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:30:52.089+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-05-05T18:31:28.598+0000] {processor.py:153} INFO - Started process (PID=9460) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:31:28.599+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:31:28.600+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:31:28.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:31:28.618+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:31:28.618+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:31:28.618+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:31:28.618+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:31:28.619+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:31:28.627+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-05-05T18:32:07.768+0000] {processor.py:153} INFO - Started process (PID=9863) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:32:07.769+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:32:07.770+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:32:07.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:32:07.790+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:32:07.790+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:32:07.790+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:32:07.790+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:32:07.791+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:32:07.799+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-05-05T18:32:47.491+0000] {processor.py:153} INFO - Started process (PID=10228) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:32:47.492+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:32:47.493+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:32:47.493+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:32:47.511+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:32:47.511+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:32:47.512+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:32:47.512+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:32:47.512+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:32:47.521+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-05-05T18:33:25.760+0000] {processor.py:153} INFO - Started process (PID=10569) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:33:25.762+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:33:25.762+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:33:25.762+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:33:25.787+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:33:25.786+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:33:25.787+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:33:25.787+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:33:25.787+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:33:25.813+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2023-05-05T18:34:04.300+0000] {processor.py:153} INFO - Started process (PID=10936) to work on /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:34:04.302+0000] {processor.py:743} INFO - Processing file /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-05T18:34:04.302+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:34:04.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:34:04.329+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:34:04.328+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-05T18:34:04.329+0000] {logging_mixin.py:137} INFO - [2023-05-05T18:34:04.329+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-05T18:34:04.329+0000] {processor.py:755} WARNING - No viable dags retrieved from /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-05T18:34:04.339+0000] {processor.py:175} INFO - Processing /usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
